/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.clickbait.plugin;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PluginFeedScraper {
    public static void main(String... args) throws Exception {
        SpringApplication.run(PluginFeedScraper.class, args);
    }
}
